# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1263433b8bf84ada606e30415e5f93026fc1259849ccf3652d1dc738b93983d32356ca351c54fbbe177de005aafeca730e062c8f618919f5f7963067243cae4

test:
  secret_key_base: b87fa283e8761c26279ec625068967f8a8f00a433b2ce031db4e8969ed5263d2a266be4aee17728b76cce05819ba1b911b7f28d16c9d0ed31f2c2ad4000e40aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
